# Generated by Django 3.1.3 on 2020-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlaces',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('imageurl', models.CharField(max_length=200)),
                ('category', models.IntegerField()),
            ],
        ),
    ]
