# Generated by Django 3.1.3 on 2020-11-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_stationcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stationCode',
            new_name='Station',
        ),
    ]
