# Generated by Django 3.1.3 on 2020-11-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0007_trainroutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
