# Generated by Django 3.1.3 on 2020-11-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0008_train_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='code',
        ),
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
