# Generated by Django 3.1.3 on 2020-11-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0009_auto_20201125_0840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='TrainRoutes',
        ),
    ]
